Mlops on Test ardeche dataset
pyronear/pyro-vision pull request #131
Opened 2021-11-28 20:45 UTC by MateoLostanlen

We have seen through our test phase in Ardeche the very poor generalization of the current model, especially on false positives. I created a test dataset from a selection of images collected in Ardeche. As we can see here the performances of the current model on this dataset are very bad:
- Accuracy : 55 %
- Precision : 47 %
- Recall : 66 %

I propose to challenge our next model on this dataset. For that purpose I propose here a standardized evaluation of the model performances in a CI to follow at best the evolution of our performances.

In my opinion to obtain good performances on this dataset is now the main objective of the vision team

2021-11-28 20:49 UTC, MateoLostanlen commented
I will probably create an ardeche dataset on using openfirev2 template as soon as the [PR](https://github.com/pyronear/pyro-vision/pull/121) is merged

2022-03-17 15:35 UTC, frgfm requested changes
Thanks for the PR!

As discussed offline:
- I suggest updating a bit the evaluation script but keeping the spirit of it
- we can add some CI job to check that the script works (in another PR) but running it fully would be too long
- I'll make a few PRs to refactor the references folder to report results in a csv file

For this PR, I suggest to rename the evaluation script (not necessarily ardeche) to "evaluate.py" and make it a bit more flexible

2022-03-17 15:35 UTC, frgfm commented on references/classification/test_ardeche.py
> +
let's have a def main()

and an argparser :)

2022-03-17 15:35 UTC, frgfm commented on references/classification/test_ardeche.py
> +
I'd suggest that the user passes the path to the data folder (can be downloaded from GDrive manually) to make this more flexible for future use.

2022-09-18 13:11 UTC, frgfm commented
With the recent refacto, I think we can close this PR

2022-09-18 15:56 UTC, MateoLostanlen commented
Yes we can !

2022-09-18 15:56 UTC, closed without merging