feat:create class to monitor pi system
pyronear/pyro-vision pull request #81
Opened 2020-07-30 16:07 UTC by fe51

This feature aims to monitor some metrics from raspberry pi system.

 In order to design a suitable system, I think some metrics could be recorded.
 As an example, in order to know if fans, heatsink are needed, cpu temperature can be recorded;
 Or, some performance about cpu usage or memory available could help to select the best raspberry pi model fitting our needs.

This is a first draft, structure/approach can be discussed and new metrics suggestion are welcomed.

Also, I think I might need to update requirements file.

2020-07-31 07:32 UTC, frgfm requested changes
Hey there, thanks for the PR!
Generally speaking, to check why some tests fail (the ones with red crosses), click on `Details` at their very right, it will take you to the code that was executed to run the test. In this case, only a few "style" changes to make!

Also, could you provide an example of usage and output for this feature please?

2020-07-31 07:32 UTC, frgfm commented on raspberryPi/monitorPi.py
> +
There is a trailing whitespace here, would you mind removing it please?

2020-07-31 07:32 UTC, frgfm commented on raspberryPi/monitorPi.py
> +
Same here

2020-07-31 07:32 UTC, frgfm commented on raspberryPi/monitorPi.py
> +
Same here

2020-07-31 07:32 UTC, frgfm commented on raspberryPi/monitorPi.py
> +                line = "{date};{t:.2f};{mem:.2f};{cpu_usage}\n".format(date=strftime("%Y-%m-%d %H:%M:%S"),t=self.cpu_temp.temperature,mem=psutil.virtual_memory().available / 1024**3,cpu_usage=psutil.
Can you add whitespaces right after commas please?

2020-07-31 07:32 UTC, frgfm commented on raspberryPi/monitorPi.py
> +                line = "{date};{t:.2f};{mem:.2f};{cpu_usage}\n".format(date=strftime("%Y-%m-%d %H:%M:%S"),t=self.cpu_temp.temperature,mem=psutil.virtual_memory().available / 1024**3,cpu_usage=psutil.
The line is too long as well, perhaps break line between commas (no need for white spaces then)

2020-07-31 07:32 UTC, frgfm commented on raspberryPi/monitorPi.py
> +
Whitespace to remove here

2020-07-31 07:32 UTC, frgfm commented on raspberryPi/monitorPi.py
> +
Whitespace to be removed

2020-07-31 07:32 UTC, frgfm commented on raspberryPi/monitorPi.py
> +    recordlogs.record(30)
Could you add a blankline at the end of the file please?

2020-08-01 10:57 UTC, fe51 commented
Hey @frgfm, thanks for the review !
I have updated the initial comment and style issues !

2020-08-01 14:46 UTC, frgfm commented
Thanks for the edits!
Regarding the cpu usage, I don't remember well how `psutils` handles this, but is it memory usage or processing capacity usage?

Two quick things that might even improve the PR:
- adding the corresponding dependencies in the `requirements.txt`
- adding a unittest to check that we actually get the expected behaviour 
Happy to help if you need some :)

2020-09-03 08:18 UTC, Akilditu reviewed
Great idea, following our last talk it seems that the next step is to agree on where this PR should be merged : 

1. Having Rasp related codes and docs within /pyronear/PyroNear/
2. Create a dedicated repository like /pyronear/raspberryPi/

2020-09-03 08:33 UTC, MateoLostanlen commented
@Akilditu and @fe51, I'm setuping the following repo https://github.com/pyronear/PyronearEngine. As discuss on the last metting this repo will regroup all work about deployment. This PR should be move there once it's ready. I let you know when it's done ;)

2020-09-03 09:47 UTC, fe51 commented
Sounds good to me !
Thank you @MateoLostanlen !

2020-09-09 15:40 UTC, frgfm commented
@fe51 following up on our last discussions about repo separation, I would suggest moving the PR to the repo that will handle RaspberryPI utilities.

If so, it could be organized as follows:
- PyroNear: core package serving our trained models and available datasets
- PyronearEngine: on-device stack for RaspberryPI using PyroNear to serve models
- XYZ: we could also set up a web-app / interface to get demos on different devices

The main idea is to use PyroNear as core API block, that can be embedded on device (raspberry PI), in the browser (live web-app) or remain on a remote server (so that it could be called by a device / service).

In this scheme, this PR might be more useful in PyronearEngine :) If so, I would suggest to close this PR and open another on the repo. Let me know your thought on this!

2020-09-17 16:43 UTC, MateoLostanlen commented
Hi @fe51, please can you close this PR and reopen it in https://github.com/pyronear/PyronearEngine ?

2020-09-18 17:14 UTC, closed without merging

2020-09-21 21:14 UTC, fe51 commented
Hi @MateoLostanlen, I have just open a new PR in PyronearEngine : https://github.com/pyronear/PyronearEngine/pull/4